### PR TITLE
Fix Bubble Sprites and Make JBubbleSprites into a Singleton

### LINKED ISSUE #57: A bubble that is floating upwards can capture an enemy.
This is not an intended feature.

### PR DESCRIPTION
**Pull request by lkroesen**
JBubbleSprites is now a Singleton.
Additionally Bubbles now have the correct sprites.

Fixes #57 aswell.

### CODE REVIEW

**Comment by 8uurg** [comment]
Seems to be fine. No big changes or any remarks from me. :+1:

**Comment by LarsStegman** [comment]
Aren't at least two people supposed to review before merging?

**Comment by lkroesen** [comment]
That's only supposed to be the master?

**Comment by LarsStegman** [comment]
That's not what we agreed upon.

**Pull request merged**
