### PR TITLE
Refactor: Move movement logic from Unit to Mover

### PR DESCRIPTION
**Pull request by LarsStegman**
I moved all the movement logic from Unit to Mover to clean up Unit. 

I also removed the unnecessary faceLeft variable in Unit. It was redundant because the direction was stored in the variable direction anyway.

Please look the changes over carefully before merging them, but don't take too long. The changes are pretty extreme, so branches which are far behind will have problems when they're going to be merged.

### CODE REVIEW

**Comment by 8uurg** [comment]
I don't agree with this, any unit is basically capable of having a position and moving around.
It is just that a certain subset (Players and Enemies) have very specific movement systems which may require a special method.

**Comment by LarsStegman** [comment]
I'll change it, so that Mover is a subclass of Unit, which makes more sense to me as well.

**Comment by LarsStegman** [comment]
I have changed it, please look at it again.

**Comment by 8uurg** [comment]
I kinda find it silly to have movement, something that all units are doing at this moment, needs its own subclass. But then again, its either this or the giant class we had at first.

I am sure we'll find a better way to solve this sooner or later, but I guess this will do for now.

**Pull request merged**
