### PR TITLE
Release 0.2

### PR DESCRIPTION
**Pull request by 8uurg**
Are we ready to release 0.2?
Final Check

>release

### CODE REVIEW

**Comment by LarsStegman** [comment]
:+1: 

Have to fix going out of the level though.

**Comment by 8uurg** [comment]
Thanks for the clarification in the chat, you are reffering to #25, not to some obsecure collision bug, was worried!

But yes, everything seems ready for version 0.2 :+1:

**Comment by lkroesen** [comment]
Pull request looking fine, added some issues to fix in the next Sprint:
https://github.com/lkroesen/BubbleBobble/issues/28
https://github.com/lkroesen/BubbleBobble/issues/26
https://github.com/lkroesen/BubbleBobble/issues/25

Test coverage is also not the desired 80% according to Cobertura, but this is due to a method we have troubles testing right now, IntelliJ line coverage is 81%, however.

**Comment by Tarovk** [comment]
Very nice. Good work everyone. PMD is still nagging about a thing or two, but it's ok

**Pull request merged**
