### PR TITLE
Revise Collisions

### PR DESCRIPTION
**Pull request by 8uurg**
I revised collisions to be cleaner (and allow certain, currently impossible things)

### CODE REVIEW

**Comment by 8uurg** [comment]
There does seem to be a tiny issue still, but I am not sure if that is caused by this or #5.

**Comment by LarsStegman** [comment]
What is the issue?

**Comment by 8uurg** [comment]
Spamming bubbles seems to hang the game, though it does not seem to get stuck in a loop.
Apparently the thread gets parked, so I guess it has something to do with the scheduler.

**Comment by 8uurg** [comment]
Problem was a concurrentmodificationexception, together with the fact that the scheduler silently stops.

**Comment by lkroesen** [comment]
There's still some checkstyle issues, please fix these.

**Comment by lkroesen** [comment]
Alright feel free to merge with dev.

**Comment by LarsStegman** [comment]
Someone other than the person who created the branch is supposed to merge it.

**Comment by lkroesen** [comment]
Due to the merge conflict I think it's better to let the creator solve the merge issues.

**Pull request merged**
