### PR TITLE
Fix the ConcurrentModificationException in the KeyListener

### PR DESCRIPTION
**Pull request by 8uurg**
I was unable to reproduce the exception after the change.
However, due to the nature of this exception I may just have been unlucky.

<bug

### CODE REVIEW

**Comment by LarsStegman** [comment]
Sorry, I still get the exception... D:

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at website.frontrow.ui.JBubbleKeyListener.update(JBubbleKeyListener.java:70)
	at website.frontrow.game.Game.tick(Game.java:56)
	at website.frontrow.Launcher.lambda$startScheduler$5(Launcher.java:105)
	at website.frontrow.Launcher$$Lambda$32/2143192188.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by 8uurg** [comment]
Welp. We may need to replace the hashmap by a concurrent one instead.
Any suggestions?

**Comment by LarsStegman** [comment]
Maybe this one?
http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html

**Comment by 8uurg** [comment]
Seems like a good choice! Want me to change it? Or will you do that yourself?

**Comment by LarsStegman** [comment]
You can do it, I'll verify the results and merge if it is ready.

**Comment by LarsStegman** [comment]
Seems like it's fixed! :+1:

**Comment by LarsStegman** [comment]
Merged it!

**Pull request merged**
