### PR TITLE
Release 0.6

### PR DESCRIPTION
**Pull request by lkroesen**
<feature

Final checks:
- [x] Checkstyle
- [x] Build
- [x] Everyone :+1:

### CODE REVIEW

**Comment by Tarovk** [comment]
Ok, while I am of course disapointed with the fact that the key bindings did not make it into the release, I have reviewed that branch, and it's just not ready for release yet. 
Therefore I agree that this should be our release for now. 
:+1:

**Comment by 8uurg** [comment]
Everything except keybindings which is not ready for release is in and working.
:+1:

**Comment by LarsStegman** [comment]
:+1: Too bad we couldn't get keybindings to work reliably though :(

**Comment by ThatFlint** [comment]
:+1:

**Comment by ThatFlint** [comment]
I guess I don't have to repeat what the others have said about the keybindings ;)

**Comment by lkroesen** [comment]
Unfortunatelly due to some unforseen bugs and a travis build failure that is hard to fix, we won't be able to release the keybindings in time, this bug has been bugging us for some time now, and it's very unfortunate we were not able to get it done, nevertheless here's my :+1:.

**Pull request merged**
