### PR TITLE
Release 1.0 beta

### PR DESCRIPTION
**Pull request by lkroesen**
<feature

Final checks:
- [x] Checkstyle
- [x] Build
- [x] Requirements
- [x] Documentation
- [x] Everyone :+1:
- [x] Merge conflict
- [x] Merge Dev

### CODE REVIEW

**Comment by 8uurg** [comment]
I fixed the only issue I had left. :+1:
(Checkstyle, PMD and FindBugs are fine too!)

**Comment by ThatFlint** [comment]
:+1:

**Comment by LarsStegman** [comment]
:+1: 

Version 1.0!!!!

**Comment by Tarovk** [comment]
:+1: Great work everyone

**Comment by 8uurg** [comment]
photo_2015-10-30_21-11-39

**Comment by lkroesen** [comment]
:+1: Let's release.

**Pull request merged**
