### PR TITLE
Release 0.4

### PR DESCRIPTION
**Pull request by 8uurg**
Final checks:
- [x] Checkstyle
- [X] Build
- [x] Everyone :+1:

### CODE REVIEW

**Comment by lkroesen** [comment]
:+1:

**Comment by 8uurg** [comment]
Obviously a :+1: from me.

**Comment by Tarovk** [comment]
:+1:

**Comment by 8uurg** [comment]
@LarsStegman and @ThatFlint 
We need you.

**Comment by LarsStegman** [comment]
I approve of the message
:+1:

**Comment by ThatFlint** [comment]
:+1: up your ass :P

**Comment by 8uurg** [comment]
And with that, we are ready to release.

**Pull request merged**
